pipeline {
  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          name: gradle
      spec:
        containers:
        - name: gradle
          image: gradle:6.3.0-jdk11
          command:
          - cat
          tty: true
        restartPolicy: Never
      """      
    }
  }
  environment {
    SCP_CREDS = credentials('scpCredentials')
    DOCKER_REGISTRY = "<< SCR Private Endpoint URI >>"
  }
  stages {
    stage('build and push docker image') {
      steps {
        container('gradle') {
          dir('eshop-backend') {
            sh """
            gradle jib --no-daemon --image ${DOCKER_REGISTRY}/eshop-backend:latest -Djib.to.auth.username=${SCP_CREDS_USR} -Djib.to.auth.password=${SCP_CREDS_PSW}
            """
          }
        }
      }
    }
  }
}